FROM node:20-alpine

RUN apk add --no-cache libc6-compat openssl python3 make g++ linux-headers

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

