services:
  postgres:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jorge
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lorito_killer_development
    volumes:
      - ./data:/var/lib/postgresql/data